### ISSUE TITLE
Add DB.connect to create connections without connection pool

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal-db#13]
`DB.connect` should return a `DB::Connection` that is not managed by a pool.
Refactor Database & Pool dependency of Connection.

**Comment by rdp** [comment]
I was actually surprised to see that DB.open returns some kind of pooled connection currently :|

**Comment by rdp** [comment]
OK I am going to comment here again. When you call 

```
DB.open("XXX") do |db|

end

```

It feels like it is returning you a connection to the db, since you can execute #query on it, etc. I guess when you call #query on `db` it must actually check out a connection from the pool, use that, then returns it to the pool? I will try and clarify the README sometime...it's just not clear here that #close closes the entire pool.  Or does it?  If you call DB.open("XX") from two different fibers will they actually share the same pool?  If that's the case then the docs really are confusing (and how do you close those connections??)

So the confusion here is people (at least me) are used to this paradigm:  you create a database pool once.  Then for each "request" you checkout a connection from that pool and use it.  However here, you never need to checkout a connection, you just "use db" as it were.  This however could make the web request paradigm a little unstable, because if each #query has to re-checkout another connection from a global pool, requests might be subject to pauses or such in the very middle of a request.  So basically every web request is going to need its own pool [?] Which isn't bad, but is a bit unclear.  Anyway once again I'll try and update the README sometime, and also file a related issue.

**Comment by bcardiff** [comment]
@rdp `DB.open` creates a new pool every time it is called. So when a server is started I would expect to create only one pool. The pool will enlarge/shrink depending on configuration. It might stall the request if there is a limited amount of connections, yes.

We try to detail a bit the pool logic at https://crystal-lang.org/docs/database/connection_pool.html feel free to send PR  either to the crystal-db/README.md or to github.com/crystal-lang/crystal-book .

**Comment by rdp** [comment]
Yeah in my head it could still use a slightly better name somehow...maybe it's just me... DB.pool or DB.open_pool etc...
