### ISSUE TITLE
possible to make DB.drivers public?

### ISSUE THREAD

**Issue by fridgerator** [crystal-lang/crystal-db#42]
In [crecto](https://github.com/fridgerator/crecto) I am currently [overriding `DB.drivers`](https://github.com/fridgerator/crecto/blob/master/src/crecto/db.cr) to be a public method so that I can assert which database driver is in use [here](https://github.com/fridgerator/crecto/blob/master/src/crecto/repo.cr#L7)

This means "crecto" needs to be required after any database library or else it breaks, and is also just bad practice.

I was wondering if it would be possible to make `DB.drivers` a public method?

**Comment by bcardiff** [comment]
I have two proposals. Either:

1. Expose schemes but not drivers. To decouple a bit implementors and consumers: `DB.schemes : Array(String) `?

Or,

2. crecto could extend DB::Driver / DB::Driver inheritors to return the Crecto::Adapters appropriate for the database. This will allow to be used per database instance rather than by loaded drivers. Currently if you have mysql loaded you can't have postgres in crecto, but that it is supported in DB.

**Comment by fridgerator** [comment]
@bcardiff Would it be possible to expose schemes?

I looked at both cases and messed around with implementing the second option but I think the first one would fit my this use case better.
