### ISSUE TITLE
Rename DB to something else?

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal-db#68]
It's very common to have a constant that represents the DB:

```crystal
DB = SomeOtherName.open(...)
```

But `DB` is taken. Maybe use the name `SQL`? DB is an interface for SQL databases, nothing else. In Go it's called `database.sql` too.

**Comment by mverzilli** [comment]
Sounds good to me, but `SQL` reads weird, eg: `SQL.open "foo"`

Maybe `CrystalDB`?

Why is naming things so hard? :P

**Comment by asterite** [comment]
Another option is `Database`. It's a bit long but they only thing you'll ever type is `Database.open`. And it frees the `DB` name.

**Comment by jhass** [comment]
Shouldn't one have an application namespace anyway? So `MyApp::DB` is entirely possible.

**Comment by bcardiff** [comment]
`RDB` is short, won't clash, but cryptic. crystal-db is _almost_ SQL free but there are some semantic to relational databases.

`SQL` reads weird, but it might be good enough.

I usually prefer singletons instead of globals.

Even if `MyApp::DB` is there, then you need to `::DB` to avoid referencing `MyApp::DB` when the code is inside `MyApp`...

**Comment by mverzilli** [comment]
So I guess the best option so far is `Database`, right? I'd go with that at least.

**Comment by bcardiff** [comment]
Any proposal for changing the `DB::Database` type to something else? Or we will have to live with `Database::Database`  :-)

**Comment by asterite** [comment]
Hm, good point. We can maybe let the existing `DB::Database` be `Database`, and nest everything else under it.

**Comment by bcardiff** [comment]
On second thoughts...

A redis shard could use `Redis::`. A s3 could use `S3::`, this are specific names that won't clash with maybe a `Cache = Redis.open...` or `Storage = S3.open...`.

But it could happen that a generic cache shard wants to use `Cache` constant, or a generic config shard wants to use `Config`. That will lead to the same situation as `DB`.

The problem is that the generic name `DB` or `Cache` is usually used implicitly when there there is one single instance of it. In an ETL app there wont be a "DB", probably there will be a `SOURCE_DB` and `TARGET_DB`.

So why don't just live with `APP_DB`, `AppDB` or even `Db`?

If the name of the constant is the only issue, it might disappear through whatever framework is used or, by getting the database through some execution context or, by picking any other of the ∞ - 1 constant names

**Comment by asterite** [comment]
@bcardiff You are right. Closing :-)

**Comment by vladfaust** [comment]
Hi there. I think a lot that `crystal-sql` would be a better name for this shard, because `db`s may be non-sql or NoSQL.

In the code:

```crystal
db = SQL::Database.new
db = SQL::Database.open
```
