### ISSUE TITLE
Move crystal-pg to github/crystal

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal-db#74]
I wonder why such an essential shard as [crystal-pg](https://github.com/will/crystal-pg) is not a part of core [Crystal organization](https://github.com/crystal-lang), but [crystal-mysql](https://github.com/crystal-lang/crystal-mysql) and [crystal-sqlite3](https://github.com/crystal-lang/crystal-sqlite3) are. Being a part of it could in theory bring more consistency, faster issues solving (because of core team working on it) and just more trust from community.

It's my opinion, and I thought it worths discussing.

**Comment by RX14** [comment]
@vladfaust because `crystal-pg` was always @will's shard and the vast majority of code is his his work. Forcing shards or popular repositories towards github organizations is to me an antipattern. If there's still a BDFL or defacto owner of the project then putting it on their github user is absolutely fine. Regardless, this is @will's decision if it was ever discussed.

**Comment by bcardiff** [comment]
If at any point crystal-pg is left without maintenance crystal-lang will fork it. But i see no benefit right now. We have interest on having a pg driver for crystal and will’s is great. It is linked in the readme as the only pg driver and that seems enough statement I think. 

Ref: https://github.com/will/crystal-pg/issues/106

**Comment by vladfaust** [comment]
@bcardiff I'm very satisfied with this:

> If at any point crystal-pg is left without maintenance crystal-lang will fork it.

Sorry for the duplicate.
