### ISSUE TITLE
[Question] Transactions not automatically rollback on exception

### ISSUE THREAD

**Issue by greenbigfrog** [crystal-lang/crystal-db#78]
Hi! I'm not sure if I'm maybe just misunderstanding something.

I'd expect an exception that occurs inside a transaction block to be automatically rescued automatically resulting in a rollback instead of raising the CONSTRAINT error.
Eg that following code would work:
```crystal
db.transaction do |tx|
  puts tx.connection.exec("INSERT INTO test (amount) VALUES (-10)")
end
```
Instead of having to use:
```crystal
db.transaction do |tx|
  begin
    puts tx.connection.exec("INSERT INTO test (amount) VALUES (-10)")
  rescue ex : PQ::PQError
    pp ex
    next tx.rollback
  end
  tx.commit
end
```

Schema:
```sql
CREATE TABLE test (
    id serial PRIMARY key,
    amount float8 NOT NULL CONSTRAINT postive_amount CHECK (amount > 0)
);
```
As said I'm not sure if this is how it's supposed to be, or I'm just missing a thought somewhere.

**Comment by bcardiff** [comment]
Hi, the transaction is probably rollbacked. But the exception is still expected to be re-raised.

https://github.com/crystal-lang/crystal-db/blob/master/src/db/begin_transaction.cr

**Comment by greenbigfrog** [comment]
Ok. So I'll still have to rescue for errors...

**Comment by bcardiff** [comment]
Yes. Imagine there is a division by zero or a key missing in block with a transaction. You want to rollback back you don’t want the exception to disappear. Otherwise it’s really hard to discover the bug.

If, on other hand, the exception is a DB::Rollback then that is indeed trapped by the transaction block. So you can use exception for control flow if you don’t have access to the transaction object.

**Comment by greenbigfrog** [comment]
Hm. Makes sense! Thanks! (and sorry for not closing the issue after your last answer 😄 )
